logging:
  path: logs/
  level:
    com:
      management:
        backend:
          mybatis:
            mapper: INFO
    org:
      mybatis: INFO

mybatis:
  mapperLocations: classpath*:mybatis/mapping/*.xml,classpath:mybatis/casadedMapping/*.xml
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: TH6ub4LJHZgvnivm
    url: jdbc:mysql://148.70.219.244:3306/backendshop_qzx?useUnicode=true&characterEncoding=UTF-8
    username: backendshop_user

#Test demo使用
qzx:
  sellerId:
  amazonAccessID: AKIAJH2EZXNXNDOS3TJQ
  amazonAccessSecret: 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
#亚马逊地址使用
amazon:
  de: https://sellercentral.amazon.de/
  en: https://sellercentral.amazon.co.uk/
  na: https://sellercentral.amazon.com/


linux:
  json: /home/ubuntu/ecommerce_backend/ecommerce-backend/static
  fileTmpPath:
  image:
    filepath: /home/ubuntu/ecommerce_backend/images/

windows:
  work:
    fileTmpPath : D:/03WorkTemp/xsd/product.xml
    image:
      filepath: D:/05Program/vue-backend-admin/static/images/
  home:
    classifyjson: F:/IvenDevelop/ECommerceWorkspace/project0714/project/static/amazonClassifyv2.json
    fileTmpPath: F:/IvenDevelop/ECommerceWorkspace/xsd/product.xml
    image:
      filepath: F:/IvenDevelop/AppWorkspace/shopping/vue-backend-admin/static/images/

