package com.management.backend.api.mybatis.model;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.creat_time
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.audit_status
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Byte auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.onsale
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Byte onsale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.level
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.user_id
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.brand
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.factory_name
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String factoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.source_area
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String sourceArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.factory_number
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String factoryNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.factory_catalog
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String factoryCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.upload_forbiden
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Byte uploadForbiden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.source_url
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String sourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.comments
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cost
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Float cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.shipping_cost
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Float shippingCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.custom_code
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String customCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.eng_desc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String engDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.declare_price
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String declarePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ch_desc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String chDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.inner_sku
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String innerSku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.suit_for_group
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Byte suitForGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_material
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String productMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.packet_material
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String packetMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.metal_type
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String metalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.jewel_type
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String jewelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.package_gross_weight
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private String packageGrossWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.has_battery
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Byte hasBattery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.package_long
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Float packageLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.package_width
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Float packageWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.package_hight
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Float packageHight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.in_store
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Long inStore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.count_per_package
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Long countPerPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type_id
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private Integer productTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.creat_time
     *
     * @return the value of product.creat_time
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.creat_time
     *
     * @param creatTime the value for product.creat_time
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.audit_status
     *
     * @return the value of product.audit_status
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.audit_status
     *
     * @param auditStatus the value for product.audit_status
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setAuditStatus(Byte auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.onsale
     *
     * @return the value of product.onsale
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Byte getOnsale() {
        return onsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.onsale
     *
     * @param onsale the value for product.onsale
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setOnsale(Byte onsale) {
        this.onsale = onsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.level
     *
     * @return the value of product.level
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.level
     *
     * @param level the value for product.level
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.user_id
     *
     * @return the value of product.user_id
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.user_id
     *
     * @param userId the value for product.user_id
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand
     *
     * @return the value of product.brand
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand
     *
     * @param brand the value for product.brand
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.factory_name
     *
     * @return the value of product.factory_name
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.factory_name
     *
     * @param factoryName the value for product.factory_name
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName == null ? null : factoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.source_area
     *
     * @return the value of product.source_area
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getSourceArea() {
        return sourceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.source_area
     *
     * @param sourceArea the value for product.source_area
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setSourceArea(String sourceArea) {
        this.sourceArea = sourceArea == null ? null : sourceArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.factory_number
     *
     * @return the value of product.factory_number
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getFactoryNumber() {
        return factoryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.factory_number
     *
     * @param factoryNumber the value for product.factory_number
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setFactoryNumber(String factoryNumber) {
        this.factoryNumber = factoryNumber == null ? null : factoryNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.factory_catalog
     *
     * @return the value of product.factory_catalog
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getFactoryCatalog() {
        return factoryCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.factory_catalog
     *
     * @param factoryCatalog the value for product.factory_catalog
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setFactoryCatalog(String factoryCatalog) {
        this.factoryCatalog = factoryCatalog == null ? null : factoryCatalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.upload_forbiden
     *
     * @return the value of product.upload_forbiden
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Byte getUploadForbiden() {
        return uploadForbiden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.upload_forbiden
     *
     * @param uploadForbiden the value for product.upload_forbiden
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setUploadForbiden(Byte uploadForbiden) {
        this.uploadForbiden = uploadForbiden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.source_url
     *
     * @return the value of product.source_url
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.source_url
     *
     * @param sourceUrl the value for product.source_url
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.comments
     *
     * @return the value of product.comments
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.comments
     *
     * @param comments the value for product.comments
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cost
     *
     * @return the value of product.cost
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Float getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cost
     *
     * @param cost the value for product.cost
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setCost(Float cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.shipping_cost
     *
     * @return the value of product.shipping_cost
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Float getShippingCost() {
        return shippingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.shipping_cost
     *
     * @param shippingCost the value for product.shipping_cost
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setShippingCost(Float shippingCost) {
        this.shippingCost = shippingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.custom_code
     *
     * @return the value of product.custom_code
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getCustomCode() {
        return customCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.custom_code
     *
     * @param customCode the value for product.custom_code
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setCustomCode(String customCode) {
        this.customCode = customCode == null ? null : customCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.eng_desc
     *
     * @return the value of product.eng_desc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getEngDesc() {
        return engDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.eng_desc
     *
     * @param engDesc the value for product.eng_desc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setEngDesc(String engDesc) {
        this.engDesc = engDesc == null ? null : engDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.declare_price
     *
     * @return the value of product.declare_price
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getDeclarePrice() {
        return declarePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.declare_price
     *
     * @param declarePrice the value for product.declare_price
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setDeclarePrice(String declarePrice) {
        this.declarePrice = declarePrice == null ? null : declarePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ch_desc
     *
     * @return the value of product.ch_desc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getChDesc() {
        return chDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ch_desc
     *
     * @param chDesc the value for product.ch_desc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setChDesc(String chDesc) {
        this.chDesc = chDesc == null ? null : chDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.inner_sku
     *
     * @return the value of product.inner_sku
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getInnerSku() {
        return innerSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.inner_sku
     *
     * @param innerSku the value for product.inner_sku
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setInnerSku(String innerSku) {
        this.innerSku = innerSku == null ? null : innerSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.suit_for_group
     *
     * @return the value of product.suit_for_group
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Byte getSuitForGroup() {
        return suitForGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.suit_for_group
     *
     * @param suitForGroup the value for product.suit_for_group
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setSuitForGroup(Byte suitForGroup) {
        this.suitForGroup = suitForGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_material
     *
     * @return the value of product.product_material
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getProductMaterial() {
        return productMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_material
     *
     * @param productMaterial the value for product.product_material
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setProductMaterial(String productMaterial) {
        this.productMaterial = productMaterial == null ? null : productMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.packet_material
     *
     * @return the value of product.packet_material
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getPacketMaterial() {
        return packetMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.packet_material
     *
     * @param packetMaterial the value for product.packet_material
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setPacketMaterial(String packetMaterial) {
        this.packetMaterial = packetMaterial == null ? null : packetMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.metal_type
     *
     * @return the value of product.metal_type
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getMetalType() {
        return metalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.metal_type
     *
     * @param metalType the value for product.metal_type
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setMetalType(String metalType) {
        this.metalType = metalType == null ? null : metalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.jewel_type
     *
     * @return the value of product.jewel_type
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getJewelType() {
        return jewelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.jewel_type
     *
     * @param jewelType the value for product.jewel_type
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setJewelType(String jewelType) {
        this.jewelType = jewelType == null ? null : jewelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.package_gross_weight
     *
     * @return the value of product.package_gross_weight
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public String getPackageGrossWeight() {
        return packageGrossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.package_gross_weight
     *
     * @param packageGrossWeight the value for product.package_gross_weight
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setPackageGrossWeight(String packageGrossWeight) {
        this.packageGrossWeight = packageGrossWeight == null ? null : packageGrossWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.has_battery
     *
     * @return the value of product.has_battery
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Byte getHasBattery() {
        return hasBattery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.has_battery
     *
     * @param hasBattery the value for product.has_battery
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setHasBattery(Byte hasBattery) {
        this.hasBattery = hasBattery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.package_long
     *
     * @return the value of product.package_long
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Float getPackageLong() {
        return packageLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.package_long
     *
     * @param packageLong the value for product.package_long
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setPackageLong(Float packageLong) {
        this.packageLong = packageLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.package_width
     *
     * @return the value of product.package_width
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Float getPackageWidth() {
        return packageWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.package_width
     *
     * @param packageWidth the value for product.package_width
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setPackageWidth(Float packageWidth) {
        this.packageWidth = packageWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.package_hight
     *
     * @return the value of product.package_hight
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Float getPackageHight() {
        return packageHight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.package_hight
     *
     * @param packageHight the value for product.package_hight
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setPackageHight(Float packageHight) {
        this.packageHight = packageHight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.in_store
     *
     * @return the value of product.in_store
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Long getInStore() {
        return inStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.in_store
     *
     * @param inStore the value for product.in_store
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setInStore(Long inStore) {
        this.inStore = inStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.count_per_package
     *
     * @return the value of product.count_per_package
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Long getCountPerPackage() {
        return countPerPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.count_per_package
     *
     * @param countPerPackage the value for product.count_per_package
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setCountPerPackage(Long countPerPackage) {
        this.countPerPackage = countPerPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type_id
     *
     * @return the value of product.product_type_id
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public Integer getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type_id
     *
     * @param productTypeId the value for product.product_type_id
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }
}