package com.management.backend.api.mybatis.model;

public class ProductWithBLOBs extends Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.englishProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] englishproducttile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.englishProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] englishproductkeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.englishProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] englishproductkeydesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.englishProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] englishproductdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.frenchProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] frenchproducttile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.frenchProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] frenchproductkeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.frenchProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] frenchproductkeydesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.frenchProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] frenchproductdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.germanProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] germanproducttile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.germanProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] germanproductkeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.germanProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] germanproductkeydesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.germanProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] germanproductdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.italyProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] italyproducttile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.italyProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] italyproductkeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.italyProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] italyproductkeydesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.italyProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] italyproductdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.spanishProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] spanishproducttile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.spanishProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] spanishproductkeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.spanishProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] spanishproductkeydesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.spanishProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] spanishproductdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.japaneseProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] japaneseproducttile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.japaneseProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] japaneseproductkeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.japaneseProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] japaneseproductkeydesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.japaneseProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] japaneseproductdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.russianProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] russianproducttile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.russianProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] russianproductkeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.russianProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] russianproductkeydesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.russianProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] russianproductdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.chineseProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] chineseproducttile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.chineseProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] chineseproductkeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.chineseProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] chineseproductkeydesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.chineseProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    private byte[] chineseproductdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.englishProductTile
     *
     * @return the value of product.englishProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getEnglishproducttile() {
        return englishproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.englishProductTile
     *
     * @param englishproducttile the value for product.englishProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setEnglishproducttile(byte[] englishproducttile) {
        this.englishproducttile = englishproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.englishProductKeyWords
     *
     * @return the value of product.englishProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getEnglishproductkeywords() {
        return englishproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.englishProductKeyWords
     *
     * @param englishproductkeywords the value for product.englishProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setEnglishproductkeywords(byte[] englishproductkeywords) {
        this.englishproductkeywords = englishproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.englishProductKeyDesc
     *
     * @return the value of product.englishProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getEnglishproductkeydesc() {
        return englishproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.englishProductKeyDesc
     *
     * @param englishproductkeydesc the value for product.englishProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setEnglishproductkeydesc(byte[] englishproductkeydesc) {
        this.englishproductkeydesc = englishproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.englishProductDesc
     *
     * @return the value of product.englishProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getEnglishproductdesc() {
        return englishproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.englishProductDesc
     *
     * @param englishproductdesc the value for product.englishProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setEnglishproductdesc(byte[] englishproductdesc) {
        this.englishproductdesc = englishproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.frenchProductTile
     *
     * @return the value of product.frenchProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getFrenchproducttile() {
        return frenchproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.frenchProductTile
     *
     * @param frenchproducttile the value for product.frenchProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setFrenchproducttile(byte[] frenchproducttile) {
        this.frenchproducttile = frenchproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.frenchProductKeyWords
     *
     * @return the value of product.frenchProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getFrenchproductkeywords() {
        return frenchproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.frenchProductKeyWords
     *
     * @param frenchproductkeywords the value for product.frenchProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setFrenchproductkeywords(byte[] frenchproductkeywords) {
        this.frenchproductkeywords = frenchproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.frenchProductKeyDesc
     *
     * @return the value of product.frenchProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getFrenchproductkeydesc() {
        return frenchproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.frenchProductKeyDesc
     *
     * @param frenchproductkeydesc the value for product.frenchProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setFrenchproductkeydesc(byte[] frenchproductkeydesc) {
        this.frenchproductkeydesc = frenchproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.frenchProductDesc
     *
     * @return the value of product.frenchProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getFrenchproductdesc() {
        return frenchproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.frenchProductDesc
     *
     * @param frenchproductdesc the value for product.frenchProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setFrenchproductdesc(byte[] frenchproductdesc) {
        this.frenchproductdesc = frenchproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.germanProductTile
     *
     * @return the value of product.germanProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getGermanproducttile() {
        return germanproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.germanProductTile
     *
     * @param germanproducttile the value for product.germanProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setGermanproducttile(byte[] germanproducttile) {
        this.germanproducttile = germanproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.germanProductKeyWords
     *
     * @return the value of product.germanProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getGermanproductkeywords() {
        return germanproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.germanProductKeyWords
     *
     * @param germanproductkeywords the value for product.germanProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setGermanproductkeywords(byte[] germanproductkeywords) {
        this.germanproductkeywords = germanproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.germanProductKeyDesc
     *
     * @return the value of product.germanProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getGermanproductkeydesc() {
        return germanproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.germanProductKeyDesc
     *
     * @param germanproductkeydesc the value for product.germanProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setGermanproductkeydesc(byte[] germanproductkeydesc) {
        this.germanproductkeydesc = germanproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.germanProductDesc
     *
     * @return the value of product.germanProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getGermanproductdesc() {
        return germanproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.germanProductDesc
     *
     * @param germanproductdesc the value for product.germanProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setGermanproductdesc(byte[] germanproductdesc) {
        this.germanproductdesc = germanproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.italyProductTile
     *
     * @return the value of product.italyProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getItalyproducttile() {
        return italyproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.italyProductTile
     *
     * @param italyproducttile the value for product.italyProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setItalyproducttile(byte[] italyproducttile) {
        this.italyproducttile = italyproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.italyProductKeyWords
     *
     * @return the value of product.italyProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getItalyproductkeywords() {
        return italyproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.italyProductKeyWords
     *
     * @param italyproductkeywords the value for product.italyProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setItalyproductkeywords(byte[] italyproductkeywords) {
        this.italyproductkeywords = italyproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.italyProductKeyDesc
     *
     * @return the value of product.italyProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getItalyproductkeydesc() {
        return italyproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.italyProductKeyDesc
     *
     * @param italyproductkeydesc the value for product.italyProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setItalyproductkeydesc(byte[] italyproductkeydesc) {
        this.italyproductkeydesc = italyproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.italyProductDesc
     *
     * @return the value of product.italyProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getItalyproductdesc() {
        return italyproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.italyProductDesc
     *
     * @param italyproductdesc the value for product.italyProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setItalyproductdesc(byte[] italyproductdesc) {
        this.italyproductdesc = italyproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.spanishProductTile
     *
     * @return the value of product.spanishProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getSpanishproducttile() {
        return spanishproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.spanishProductTile
     *
     * @param spanishproducttile the value for product.spanishProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setSpanishproducttile(byte[] spanishproducttile) {
        this.spanishproducttile = spanishproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.spanishProductKeyWords
     *
     * @return the value of product.spanishProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getSpanishproductkeywords() {
        return spanishproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.spanishProductKeyWords
     *
     * @param spanishproductkeywords the value for product.spanishProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setSpanishproductkeywords(byte[] spanishproductkeywords) {
        this.spanishproductkeywords = spanishproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.spanishProductKeyDesc
     *
     * @return the value of product.spanishProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getSpanishproductkeydesc() {
        return spanishproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.spanishProductKeyDesc
     *
     * @param spanishproductkeydesc the value for product.spanishProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setSpanishproductkeydesc(byte[] spanishproductkeydesc) {
        this.spanishproductkeydesc = spanishproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.spanishProductDesc
     *
     * @return the value of product.spanishProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getSpanishproductdesc() {
        return spanishproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.spanishProductDesc
     *
     * @param spanishproductdesc the value for product.spanishProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setSpanishproductdesc(byte[] spanishproductdesc) {
        this.spanishproductdesc = spanishproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.japaneseProductTile
     *
     * @return the value of product.japaneseProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getJapaneseproducttile() {
        return japaneseproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.japaneseProductTile
     *
     * @param japaneseproducttile the value for product.japaneseProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setJapaneseproducttile(byte[] japaneseproducttile) {
        this.japaneseproducttile = japaneseproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.japaneseProductKeyWords
     *
     * @return the value of product.japaneseProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getJapaneseproductkeywords() {
        return japaneseproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.japaneseProductKeyWords
     *
     * @param japaneseproductkeywords the value for product.japaneseProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setJapaneseproductkeywords(byte[] japaneseproductkeywords) {
        this.japaneseproductkeywords = japaneseproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.japaneseProductKeyDesc
     *
     * @return the value of product.japaneseProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getJapaneseproductkeydesc() {
        return japaneseproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.japaneseProductKeyDesc
     *
     * @param japaneseproductkeydesc the value for product.japaneseProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setJapaneseproductkeydesc(byte[] japaneseproductkeydesc) {
        this.japaneseproductkeydesc = japaneseproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.japaneseProductDesc
     *
     * @return the value of product.japaneseProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getJapaneseproductdesc() {
        return japaneseproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.japaneseProductDesc
     *
     * @param japaneseproductdesc the value for product.japaneseProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setJapaneseproductdesc(byte[] japaneseproductdesc) {
        this.japaneseproductdesc = japaneseproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.russianProductTile
     *
     * @return the value of product.russianProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getRussianproducttile() {
        return russianproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.russianProductTile
     *
     * @param russianproducttile the value for product.russianProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setRussianproducttile(byte[] russianproducttile) {
        this.russianproducttile = russianproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.russianProductKeyWords
     *
     * @return the value of product.russianProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getRussianproductkeywords() {
        return russianproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.russianProductKeyWords
     *
     * @param russianproductkeywords the value for product.russianProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setRussianproductkeywords(byte[] russianproductkeywords) {
        this.russianproductkeywords = russianproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.russianProductKeyDesc
     *
     * @return the value of product.russianProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getRussianproductkeydesc() {
        return russianproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.russianProductKeyDesc
     *
     * @param russianproductkeydesc the value for product.russianProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setRussianproductkeydesc(byte[] russianproductkeydesc) {
        this.russianproductkeydesc = russianproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.russianProductDesc
     *
     * @return the value of product.russianProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getRussianproductdesc() {
        return russianproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.russianProductDesc
     *
     * @param russianproductdesc the value for product.russianProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setRussianproductdesc(byte[] russianproductdesc) {
        this.russianproductdesc = russianproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.chineseProductTile
     *
     * @return the value of product.chineseProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getChineseproducttile() {
        return chineseproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.chineseProductTile
     *
     * @param chineseproducttile the value for product.chineseProductTile
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setChineseproducttile(byte[] chineseproducttile) {
        this.chineseproducttile = chineseproducttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.chineseProductKeyWords
     *
     * @return the value of product.chineseProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getChineseproductkeywords() {
        return chineseproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.chineseProductKeyWords
     *
     * @param chineseproductkeywords the value for product.chineseProductKeyWords
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setChineseproductkeywords(byte[] chineseproductkeywords) {
        this.chineseproductkeywords = chineseproductkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.chineseProductKeyDesc
     *
     * @return the value of product.chineseProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getChineseproductkeydesc() {
        return chineseproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.chineseProductKeyDesc
     *
     * @param chineseproductkeydesc the value for product.chineseProductKeyDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setChineseproductkeydesc(byte[] chineseproductkeydesc) {
        this.chineseproductkeydesc = chineseproductkeydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.chineseProductDesc
     *
     * @return the value of product.chineseProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public byte[] getChineseproductdesc() {
        return chineseproductdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.chineseProductDesc
     *
     * @param chineseproductdesc the value for product.chineseProductDesc
     *
     * @mbggenerated Sun Jun 23 18:06:33 CST 2019
     */
    public void setChineseproductdesc(byte[] chineseproductdesc) {
        this.chineseproductdesc = chineseproductdesc;
    }
}