package com.management.backend.api.mybatis.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    private Long qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telephone
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    private Long telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.amount
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_name
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_passwd
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    private String loginPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.photo_location
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    private String photoLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public Long getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public void setQq(Long qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telephone
     *
     * @return the value of user.telephone
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public Long getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telephone
     *
     * @param telephone the value for user.telephone
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public void setTelephone(Long telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.amount
     *
     * @return the value of user.amount
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.amount
     *
     * @param amount the value for user.amount
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_name
     *
     * @return the value of user.login_name
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_name
     *
     * @param loginName the value for user.login_name
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_passwd
     *
     * @return the value of user.login_passwd
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public String getLoginPasswd() {
        return loginPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_passwd
     *
     * @param loginPasswd the value for user.login_passwd
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public void setLoginPasswd(String loginPasswd) {
        this.loginPasswd = loginPasswd == null ? null : loginPasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.photo_location
     *
     * @return the value of user.photo_location
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public String getPhotoLocation() {
        return photoLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.photo_location
     *
     * @param photoLocation the value for user.photo_location
     *
     * @mbggenerated Mon Jun 24 21:47:09 CST 2019
     */
    public void setPhotoLocation(String photoLocation) {
        this.photoLocation = photoLocation == null ? null : photoLocation.trim();
    }
}